### ISSUE TITLE
Duplicate cards

### ISSUE THREAD

**Issue by brownr425** [carolinecavaliere/Palace#17]
As the code is currently written, sometimes the deck will produce a duplicate card of one that a player already has. It seems to happen randomly and without a pattern, but it seems like it is a problem with the copying of the cards through the copy constructor in PalaceGameState. Each time that constructor is used, a new deck is created with all new cards. As a result, there is a possibility that the shuffled deck could give you a card that you already have. If the copying gets fixed, then the duplicates should as well.

**Comment by carolinecavaliere** [comment]
will not fix- we genuinely could not figure out how this was happening. Even after getting Professor Vegdahl's help during office hours and spending many hours with the debugger, every change we made to solve the issue (including changes to the copy constructor for PalaceDeckOfCards, the drawCard() method, changing the instance variables from static to private, altering the way that the adders/removers function, altering the way that takePile functions, along with a few other minor changes) resulted in many other fatal bugs that we didn't have before. Sometimes there are no duplicate cards at all in a game, and sometimes there are quite a few. We could never grasp what the pattern was.
